plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.group

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    if (project.minecraft_version == '26.3') {
        implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version_26_3}"
    } else {
        include implementation('net.fabricmc.fabric-api:fabric-api-base:2.0.4+ece063239e')
        include implementation('net.fabricmc.fabric-api:fabric-resource-loader-v1:2.0.13+9edec1269e')
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.minecraft_version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version, 'minecraft_version': project.minecraft_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}
